Changes output file name.

diff --git a/.github/workflows/behave-test-template.yml b/.github/workflows/behave-test-template.yml
--- a/.github/workflows/behave-test-template.yml
+++ b/.github/workflows/behave-test-template.yml
@@ -25,20 +25,22 @@ jobs:
         run: |
           echo "y" | uv run trustpoint/manage.py reset_db
 
-      - name: Run Behave Tests and Generate HTML Report for ${{ inputs.feature_file }}
+      - name: Run Behave Tests and Generate HTML Report for ${{ inputs.feature_file }}.feature
         run: |
-          uv run trustpoint/manage.py behave ${{ inputs.feature_file }} || echo "Test failed"
+          uv run trustpoint/manage.py behave \
+          trustpoint/features/${{ inputs.feature_file }}.feature \
+          -o ${{ inputs.feature_file }}-report.html || echo "Test failed"
 
       - name: Upload Test Report
         uses: actions/upload-artifact@v4
         if: always()
         with:
-          name: behave-html-report
-          path: behave-report.html
+          name: ${{ inputs.feature_file }}-html-report
+          path: ${{ inputs.feature_file }}-report.html
 
       - name: Fail Job if Tests Failed
         run: |
-          if grep -q ">Failed:\s[1-99]" behave-report.html; then
+          if grep -q ">Failed:\s[1-99]" ${{ inputs.feature_file }}-report.html; then
             echo "❌ Behave tests failed! Failing job."
             exit 1
           fi
