Add report to PR if tests fail.

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -37,7 +37,6 @@ jobs:
           name: pytest-reports
           path: reports/
 
-      # https://pypi.org/project/pytest-md-report/
       - name: Display Summary in GitHub Actions
         run: |
           echo "<details><summary>Pytest Report</summary>" >> $GITHUB_STEP_SUMMARY
@@ -46,9 +45,17 @@ jobs:
           echo "" >> $GITHUB_STEP_SUMMARY
           echo "</details>" >> $GITHUB_STEP_SUMMARY
 
-      - name: Fail Job if Tests Failed
-        run: |
-          if grep -q "errors="[1-9]" failures="[1-9]" skipped="[1-9]"" reports/junit-report.xml; then
-            echo "❌ Pytest failed! Failing job."
-            exit 1
-          fi
+      - name: Render the report to the PR when tests fail
+        uses: marocchino/sticky-pull-request-comment@v2
+        if: failure()
+        with:
+          header: test-report
+          recreate: true
+          path: md-report.md
+
+#      - name: Fail Job if Tests Failed
+#        run: |
+#          if grep -q "errors="[1-9]" failures="[1-9]" skipped="[1-9]"" reports/junit-report.xml; then
+#            echo "❌ Pytest failed! Failing job."
+#            exit 1
+#          fi
